name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '24 3 * * 5' # every friday morning at 3:24h

jobs:
  build:
    name: "${{ matrix.configurations.name }}"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        configurations:
          - name: "gcc 12"
            compiler: gcc
          - name: "clang 14"
            compiler: clang

    steps:
    - uses: actions/checkout@v3

    - name: Install gcc-12
      if: matrix.configurations.compiler == 'gcc'
      run: |
        sudo apt install -y gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 110 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12

    - name: Install clang-14
      if: matrix.configurations.compiler == 'clang'
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-14 main'
        sudo apt update
        sudo apt install -y clang-14 libc++-14-dev libc++abi-14-dev
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-14 110

    - name: Configure CMake
      run: cmake -S . -B ../build

    - name: Build
      run: cmake --build ../build
